version: "3.8"
services:
  postgres:
    image: postgres:13.10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nothing
      - POSTGRES_DB=grocery-app
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:nothing@postgres:5432/grocery?schema=public
      - JWT_SECRET=grocers123
    command: sh -c "npx prisma migrate deploy && npm start"

volumes:
  postgres:
